##Custom Properties
api:
  base-path: /api/v1
## profile active
spring:
  application:
    name: onion
  profiles:
    active: dev
server:
  servlet:
    context-path: /onion${api.basepath}
#log config
log:
  file:
    path: ./logs
##actuator configs
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics
  endpoint:
    health:
      enabled: 'true'
      show-details: always